import type { BattleReport } from './report.ts';

// Demo battle fixtures for report UI. Not generated by CombatResolver.
// Values below are explicit presentation/test data and are not Nemexia combat formulas.
export const DEMO_BATTLE_REPORTS: readonly BattleReport[] = [
  {
    id: 'battle-demo-attacker-victory',
    timestamp: '2026-09-03T15:42:00.000Z',
    missionType: 'attack',
    attacker: {
      playerId: 'player-aster',
      playerName: 'Aster Command',
      planetName: 'Helion 01',
      coordinates: '[1:1:1]',
      race: 'Астеры',
      side: 'attacker',
    },
    defender: {
      playerId: 'player-vega',
      playerName: 'Vega Directorate',
      planetName: 'Vega IX',
      coordinates: '[1:12:7]',
      race: 'Директорат',
      side: 'defender',
    },
    winner: 'attacker',
    roundCount: 5,
    attackerForce: {
      populationBefore: 420,
      populationAfter: 173,
      activeCommanderId: 'judge',
      stacks: [
        { entityId: 'scout', countBefore: 100, countAfter: 42, destroyed: 58 },
        { entityId: 'cruiser', countBefore: 24, countAfter: 11, destroyed: 13 },
        { entityId: 'judge', countBefore: 1, countAfter: 1, destroyed: 0 },
      ],
      modifiers: { formation: 'Ударная линия', commanderSnapshot: 'judge' },
    },
    defenderForce: {
      populationBefore: 510,
      populationAfter: 0,
      stacks: [
        { entityId: 'defender', countBefore: 32, countAfter: 0, destroyed: 32 },
        { entityId: 'battleship', countBefore: 8, countAfter: 0, destroyed: 8 },
      ],
      defenses: [
        { entityId: 'laser-turret', countBefore: 50, countAfter: 0, destroyed: 50 },
        { entityId: 'tower-shield', countBefore: 1, countAfter: 0, destroyed: 1, shield: 0 },
      ],
    },
    rounds: [
      {
        index: 1,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'scout', actorCount: 100,
            targetSide: 'defender', targetEntityId: 'laser-turret', targetCount: 50,
            actionType: 'attack', attackValue: 12_400, damage: 8_210, destroyedCount: 3,
          },
          {
            sequence: 2,
            actorSide: 'defender', actorEntityId: 'laser-turret', actorCount: 47,
            targetSide: 'attacker', targetEntityId: 'scout', targetCount: 100,
            actionType: 'attack', attackValue: 10_900, damage: 7_200, destroyedCount: 8,
          },
        ],
      },
      {
        index: 2,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'cruiser', actorCount: 24,
            targetSide: 'defender', targetEntityId: 'tower-shield', targetCount: 1,
            actionType: 'attack', attackValue: 18_800, damage: 13_400,
            shieldBefore: 15_000, shieldAfter: 8_300,
          },
          {
            sequence: 2,
            actorSide: 'attacker', actorEntityId: 'judge', actorCount: 1,
            targetSide: 'defender', targetEntityId: 'battleship', targetCount: 8,
            actionType: 'ability', commanderAbilityId: 'judge',
            note: 'Способность зафиксирована в отчёте как активная. Эффект в PR #30 не рассчитывается.',
          },
        ],
      },
      {
        index: 3,
        events: [
          {
            sequence: 1,
            actorSide: 'defender', actorEntityId: 'battleship', actorCount: 6,
            targetSide: 'attacker', targetEntityId: 'cruiser', targetCount: 19,
            actionType: 'attack', attackValue: 25_600, damage: 17_900,
            armorBefore: 12, armorAfter: 12, destroyedCount: 5,
          },
          {
            sequence: 2,
            actorSide: 'attacker', actorEntityId: 'scout', actorCount: 70,
            targetSide: 'defender', targetEntityId: 'laser-turret', targetCount: 28,
            actionType: 'attack', damage: 19_400, destroyedCount: 16,
          },
        ],
      },
      {
        index: 4,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'cruiser', actorCount: 14,
            targetSide: 'defender', targetEntityId: 'battleship', targetCount: 4,
            actionType: 'attack', attackValue: 31_200, damage: 26_000,
            lifeBefore: 74_000, lifeAfter: 28_000, destroyedCount: 2,
          },
          {
            sequence: 2,
            actorSide: 'defender', actorEntityId: 'defender', actorCount: 11,
            targetSide: 'attacker', targetEntityId: 'scout', targetCount: 54,
            actionType: 'attack', destroyedCount: 12,
          },
        ],
      },
      {
        index: 5,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'scout', actorCount: 42,
            targetSide: 'defender', targetEntityId: 'defender', targetCount: 6,
            actionType: 'destroyed', damage: 22_600, destroyedCount: 6,
            note: 'Последняя оборонительная группа уничтожена.',
          },
        ],
        attackerSnapshot: {
          stacks: [
            { entityId: 'scout', countBefore: 100, countAfter: 42, destroyed: 58 },
            { entityId: 'cruiser', countBefore: 24, countAfter: 11, destroyed: 13 },
            { entityId: 'judge', countBefore: 1, countAfter: 1, destroyed: 0 },
          ],
        },
        defenderSnapshot: {
          stacks: [
            { entityId: 'defender', countBefore: 32, countAfter: 0, destroyed: 32 },
            { entityId: 'battleship', countBefore: 8, countAfter: 0, destroyed: 8 },
          ],
          defenses: [
            { entityId: 'laser-turret', countBefore: 50, countAfter: 0, destroyed: 50 },
            { entityId: 'tower-shield', countBefore: 1, countAfter: 0, destroyed: 1, shield: 0 },
          ],
        },
      },
    ],
    experience: 84,
    debris: 291_027,
    resources: { metal: 42_000, minerals: 18_500, gas: 3_200 },
    metadata: {
      source: 'demo-fixture',
      note: 'Explicit report data for Battle UI. Not generated by CombatResolver.',
    },
  },
  {
    id: 'battle-demo-defender-victory',
    timestamp: '2026-09-02T20:16:00.000Z',
    missionType: 'defense',
    attacker: {
      playerId: 'player-raider',
      playerName: 'Orion Raiders',
      planetName: 'Orion Gate',
      coordinates: '[1:8:4]',
      race: 'Рейдеры',
      side: 'attacker',
    },
    defender: {
      playerId: 'player-aster',
      playerName: 'Aster Command',
      planetName: 'Helion 01',
      coordinates: '[1:1:1]',
      race: 'Астеры',
      side: 'defender',
    },
    winner: 'defender',
    roundCount: 4,
    attackerForce: {
      populationBefore: 360,
      populationAfter: 0,
      stacks: [
        { entityId: 'scout', countBefore: 60, countAfter: 0, destroyed: 60 },
        { entityId: 'destroyer', countBefore: 8, countAfter: 0, destroyed: 8 },
      ],
    },
    defenderForce: {
      populationBefore: 445,
      populationAfter: 231,
      activeCommanderId: 'reanimator',
      stacks: [
        { entityId: 'cruiser', countBefore: 18, countAfter: 10, destroyed: 8 },
        { entityId: 'reanimator', countBefore: 1, countAfter: 1, destroyed: 0 },
      ],
      defenses: [
        { entityId: 'ballistic-turret', countBefore: 80, countAfter: 34, destroyed: 46 },
        { entityId: 'plasma-turret', countBefore: 24, countAfter: 9, destroyed: 15 },
      ],
    },
    rounds: [
      {
        index: 1,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'destroyer', actorCount: 8,
            targetSide: 'defender', targetEntityId: 'ballistic-turret', targetCount: 80,
            actionType: 'attack', attackValue: 41_000, damage: 31_500, destroyedCount: 18,
          },
          {
            sequence: 2,
            actorSide: 'defender', actorEntityId: 'plasma-turret', actorCount: 24,
            targetSide: 'attacker', targetEntityId: 'destroyer', targetCount: 8,
            actionType: 'attack', damage: 46_200, destroyedCount: 2,
          },
        ],
      },
      {
        index: 2,
        events: [
          {
            sequence: 1,
            actorSide: 'defender', actorEntityId: 'reanimator', actorCount: 1,
            targetSide: 'defender', targetEntityId: 'cruiser', targetCount: 14,
            actionType: 'ability', commanderAbilityId: 'reanimator',
            note: 'Отчёт отмечает активацию командира; восстановление не вычисляется этим fixture.',
          },
          {
            sequence: 2,
            actorSide: 'attacker', actorEntityId: 'scout', actorCount: 44,
            targetSide: 'defender', targetEntityId: 'cruiser', targetCount: 14,
            actionType: 'attack', destroyedCount: 4,
          },
        ],
      },
      {
        index: 3,
        events: [
          {
            sequence: 1,
            actorSide: 'defender', actorEntityId: 'cruiser', actorCount: 10,
            targetSide: 'attacker', targetEntityId: 'scout', targetCount: 31,
            actionType: 'attack', attackValue: 33_600, damage: 28_800, destroyedCount: 22,
          },
          {
            sequence: 2,
            actorSide: 'defender', actorEntityId: 'plasma-turret', actorCount: 12,
            targetSide: 'attacker', targetEntityId: 'destroyer', targetCount: 3,
            actionType: 'attack', destroyedCount: 3,
          },
        ],
      },
      {
        index: 4,
        events: [
          {
            sequence: 1,
            actorSide: 'defender', actorEntityId: 'ballistic-turret', actorCount: 34,
            targetSide: 'attacker', targetEntityId: 'scout', targetCount: 9,
            actionType: 'destroyed', damage: 11_400, destroyedCount: 9,
          },
        ],
      },
    ],
    experience: 61,
    debris: 184_500,
    metadata: {
      source: 'demo-fixture',
      note: 'Explicit defender-victory fixture with defenses and commander snapshot.',
    },
  },
  {
    id: 'battle-demo-round-limit-draw',
    timestamp: '2026-09-01T10:05:00.000Z',
    missionType: 'attack',
    attacker: {
      playerId: 'player-aster',
      playerName: 'Aster Command',
      planetName: 'Helion 01',
      coordinates: '[1:1:1]',
      race: 'Астеры',
      side: 'attacker',
    },
    defender: {
      playerId: 'player-lyra',
      playerName: 'Lyra Collective',
      planetName: 'Lyra Outpost',
      coordinates: '[1:19:3]',
      race: 'Коллектив',
      side: 'defender',
    },
    winner: 'draw',
    roundCount: 5,
    attackerForce: {
      populationBefore: 280,
      populationAfter: 121,
      stacks: [
        { entityId: 'scout', countBefore: 90, countAfter: 37, destroyed: 53 },
        { entityId: 'cruiser', countBefore: 14, countAfter: 7, destroyed: 7 },
      ],
    },
    defenderForce: {
      populationBefore: 300,
      populationAfter: 108,
      stacks: [
        { entityId: 'defender', countBefore: 30, countAfter: 12, destroyed: 18 },
        { entityId: 'battleship', countBefore: 8, countAfter: 3, destroyed: 5 },
      ],
    },
    rounds: [
      {
        index: 1,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'scout',
            targetSide: 'defender', targetEntityId: 'defender',
            actionType: 'attack', damage: 9_200, destroyedCount: 4,
          },
        ],
      },
      {
        index: 2,
        events: [
          {
            sequence: 1,
            actorSide: 'defender', actorEntityId: 'battleship',
            targetSide: 'attacker', targetEntityId: 'cruiser',
            actionType: 'attack', attackValue: 21_500, destroyedCount: 2,
          },
        ],
      },
      {
        index: 3,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'cruiser',
            targetSide: 'defender', targetEntityId: 'battleship',
            actionType: 'attack', armorBefore: 9, armorAfter: 9, destroyedCount: 2,
          },
        ],
      },
      {
        index: 4,
        events: [
          {
            sequence: 1,
            actorSide: 'defender', actorEntityId: 'defender',
            targetSide: 'attacker', targetEntityId: 'scout',
            actionType: 'attack', damage: 14_100, destroyedCount: 18,
          },
        ],
      },
      {
        index: 5,
        events: [
          {
            sequence: 1,
            actorSide: 'attacker', actorEntityId: 'scout', actorCount: 37,
            targetSide: 'defender', targetEntityId: 'defender', targetCount: 12,
            actionType: 'status',
            note: 'Достигнут лимит demo-отчёта: 5 раундов. Победитель не определён.',
          },
        ],
      },
    ],
    metadata: {
      source: 'demo-fixture',
      maxRounds: 5,
      note: 'Explicit draw fixture ending at the configured round limit.',
    },
  },
] as const;

export const DEMO_BATTLE_REPORT_IDS = DEMO_BATTLE_REPORTS.map((report) => report.id);
