import { getFactionDefenseCatalog, getFactionShipCatalog } from '../combat/faction-catalog.ts';
import { createDefaultCombatTechnologies } from '../combat/technologies.ts';
import { createDefaultCombatPriority } from '../combat/priority.ts';
import { createSeededCombatRng, resolveCombat } from '../combat/resolver.ts';
import type { BattleReport, BattleWinner } from '../combat/report.ts';
import type { CombatInput, CombatStackInput } from '../combat/simulator.ts';
import { resolvePlanetSiege } from '../combat/planet-siege.ts';
import { getUniverseTimedObjectSchedule } from '../universe/runtime.ts';
import { PIRATE_BASE_SHIPS, PIRATE_CATALOG, PIRATE_CATALOG_BY_ID, type PirateBaseShipId, type PirateShipDefinition } from './catalog.ts';
import {
  aggregatePirateRaidChance,
  calculatePirateActivityRatio,
  canUsePiratePlanetBreaker,
  pirateContactCycleKey,
  PIRATE_PLANET_BREAKER_APPEARANCE_CHANCE,
  pirateRaidChance,
  pirateRaidPopulationMultiplier,
  resolvePirateRaidCycle,
} from './contact-rules.ts';
import {
  calculatePirateEliminationPopulationBudget,
  createPirateProfile,
  expectedPirateTierShares,
  pirateLevelForResourcePoints,
  type PirateProfile,
  type PirateTierShares,
} from './profile.ts';
import type { CombatFactionId } from '../combat/factions.ts';
import pirateAbilitySourceFixture from '../combat/source-fixtures/ship-abilities.json' with { type: 'json' };

/** The explicit input corpus is generated by stable case/run indices, never Math.random. */
export const PIRATE_BALANCE_SEED_CORPUS = Object.freeze({
  version: 'pirate-operations-v1-balance-seeds',
  prefix: 'pirate-ops-v1',
  firstIndex: 0,
  runIndexEncoding: 'base-10, zero-padded to 4 digits',
  scenarioEncoding: 'stable JSON tuple [kind, scoreBand, faction, pirateClass, formation, playerClasses, attackerTechnologyLevel]',
});

export const PIRATE_BALANCE_SCORE_BANDS = Object.freeze([
  { id: 'low', totalPoints: 1_000, resourcePoints: 1_000, battlePoints: 0, expectedTierShares: { 1: 100, 2: 0, 3: 0 } },
  { id: 'early', totalPoints: 10_000, resourcePoints: 10_000, battlePoints: 0, expectedTierShares: { 1: 85, 2: 15, 3: 0 } },
  { id: 'mid', totalPoints: 100_000, resourcePoints: 100_000, battlePoints: 0, expectedTierShares: { 1: 70, 2: 25, 3: 5 } },
  { id: 'advanced', totalPoints: 1_000_000, resourcePoints: 1_000_000, battlePoints: 0, expectedTierShares: { 1: 15, 2: 25, 3: 60 } },
  { id: 'high', totalPoints: 10_000_000, resourcePoints: 10_000_000, battlePoints: 0, expectedTierShares: { 1: 5, 2: 15, 3: 80 } },
] as const);

export const PIRATE_BALANCE_ATTACKER_TECH_BANDS = Object.freeze([0, 5, 10] as const);

const FACTIONS: readonly CombatFactionId[] = ['aegis', 'synod', 'veyra'];
const ORDINARY_CLASSES = ['scout', 'cruiser', 'defender', 'battleship', 'destroyer', 'bomber'] as const;
const PIRATE_BY_CLASS = Object.fromEntries(PIRATE_BASE_SHIPS.map((ship) => [ship.ordinaryClass, ship.id])) as Record<typeof ORDINARY_CLASSES[number], PirateBaseShipId>;
const FLEET_POPULATION = 1_000;
const MAX_ROUNDS = 8 as const;
const Z95 = 1.959963984540054;

/** Mirrors the resolver's documented ordinary-class matchup coefficients for case selection only. */
const MATCHUP: Readonly<Record<typeof ORDINARY_CLASSES[number], Readonly<Record<typeof ORDINARY_CLASSES[number], number>>>> = Object.freeze({
  scout: Object.freeze({ scout: 0.70, cruiser: 1, defender: 1.70, battleship: 1.70, destroyer: 1, bomber: 1 }),
  cruiser: Object.freeze({ scout: 1.70, cruiser: 0.70, defender: 1.70, battleship: 0.70, destroyer: 1, bomber: 1 }),
  defender: Object.freeze({ scout: 0.70, cruiser: 1, defender: 0.70, battleship: 1, destroyer: 1, bomber: 1.70 }),
  battleship: Object.freeze({ scout: 1, cruiser: 1.70, defender: 1.70, battleship: 0.70, destroyer: 0.70, bomber: 1 }),
  destroyer: Object.freeze({ scout: 1, cruiser: 1, defender: 1, battleship: 1.70, destroyer: 0.70, bomber: 0.70 }),
  bomber: Object.freeze({ scout: 1, cruiser: 0.70, defender: 1, battleship: 1, destroyer: 1.70, bomber: 0.70 }),
});

export type PirateBalanceWinnerCounts = Readonly<Record<BattleWinner, number>>;
export type PirateBalanceMatchup = Readonly<{
  key: string;
  scoreBand: string;
  totalPoints: number;
  pirateLevel: number;
  attackerTechnologyLevel: 0 | 5 | 10;
  faction: CombatFactionId;
  pirateShipId: PirateBaseShipId;
  formation: 'mirror' | 'counter' | 'single' | 'pair' | 'mixed';
  playerClasses: readonly typeof ORDINARY_CLASSES[number][];
  counterClass: typeof ORDINARY_CLASSES[number];
  requestedPopulation: number;
  attackerActualPopulation: number;
  pirateTargetPopulation: number;
  piratePopulationError: number;
  defenderActualPopulation: number;
  runs: number;
  winnerCounts: PirateBalanceWinnerCounts;
  attackerWinRate: number;
  attackerWinRate95: readonly [number, number];
  drawRate: number;
  drawRate95: readonly [number, number];
  defenderWinRate: number;
  defenderWinRate95: readonly [number, number];
  attackerResidualMedian: number;
  attackerResidualRange: readonly [number, number];
  defenderResidualMedian: number;
  defenderResidualRange: readonly [number, number];
  meanRounds: number;
  seedCorpus: Readonly<{ first: string; last: string; hashFnv1a32: string }>;
}>;

export type PirateBalanceRaidEstimate = Readonly<{
  q: number;
  chancePerContact: number;
  horizonHours: 24 | 72;
  independentSystems: 1 | 2 | 3 | 5;
  owners: number;
  contactsProcessed: number;
  expectedContactsPerOwner: number;
  raidRatePerSystem: number;
  systemsWithZeroRate: number;
  systemsWithOneRate: number;
  systemsWithMultipleRate: number;
  systemsWithAtLeastOneRate95: readonly [number, number];
  raidRatePerOwner: number;
  ownersWithZeroRaids: number;
  ownersWithOneRaid: number;
  ownersWithMultipleRaids: number;
  ownersWithZeroRate: number;
  ownersWithOneRate: number;
  ownersWithMultipleRate: number;
  ownersWithAtLeastOneRate95: readonly [number, number];
  raidCountRange: readonly [number, number];
  aggregateIndependentSystemProbability: number;
  seedCorpus: Readonly<{ first: string; last: string; hashFnv1a32: string }>;
}>;

export type PirateBalanceSiegeEstimate = Readonly<{
  defenderFaction: CombatFactionId;
  defenderComposition: 'fleet-only' | 'defense-only' | 'mixed' | 'empty';
  defenderPopulation: 0 | 1_999 | 2_000;
  pirateShipId: PirateBaseShipId;
  ownerTotalPoints: number;
  breakerEligible: boolean;
  runs: number;
  breakerAppearances: number;
  breakerAppearanceRate: number;
  breakerAppearanceRate95: readonly [number, number];
  battleWins: number;
  battleWinRate: number;
  battleWinRate95: readonly [number, number];
  defenderWins: number;
  defenderWinRate: number;
  defenderWinRate95: readonly [number, number];
  draws: number;
  drawRate: number;
  drawRate95: readonly [number, number];
  attackerResidualMedian: number;
  attackerResidualRange: readonly [number, number];
  defenderResidualMedian: number;
  defenderResidualRange: readonly [number, number];
  planetLosses: number;
  planetLossRate: number;
  planetLossRate95: readonly [number, number];
  seedCorpus: Readonly<{ first: string; last: string; hashFnv1a32: string }>;
}>;

export type PirateBalanceSimulation = Readonly<{
  seedCorpus: typeof PIRATE_BALANCE_SEED_CORPUS;
  runsPerMatchup: number;
  matchups: readonly PirateBalanceMatchup[];
  profileTierEstimates: readonly PirateProfileTierEstimate[];
  raidEstimates: readonly PirateBalanceRaidEstimate[];
  siegeEstimates: readonly PirateBalanceSiegeEstimate[];
  catalogSourceMedians: readonly PirateCatalogMedianRow[];
  sourceAbilityRows: readonly PirateSourceAbilityRow[];
  levelStats: readonly PirateLevelStats[];
  budgetCheck: Readonly<{ sentCombatPopulation: number; requestedPopulation: number; cases: readonly { shipId: PirateBaseShipId; actualPopulation: number; absoluteError: number; populationPerShip: number; unitCount: number }[] }>;
}>;

export type PirateSourceAbilityRow = Readonly<{
  pirateShipId: PirateBaseShipId;
  sourceId: string;
  sourceByFaction: Readonly<Record<CombatFactionId, string>>;
  commonAbilityMetricMedians: readonly Readonly<{
    abilityClass: string;
    metricLabel: string;
    factionValues: Readonly<Record<CombatFactionId, string>>;
    medianSourcePercent: number;
  }>[];
}>;

export type PirateProfileTierEstimate = Readonly<{
  totalPoints: number;
  resourcePoints: number;
  runs: number;
  expectedShares: Readonly<Record<1 | 2 | 3, number>>;
  observedShares: Readonly<Record<1 | 2 | 3, number>>;
  confidence95: Readonly<Record<1 | 2 | 3, readonly [number, number]>>;
  seedCorpus: Readonly<{ first: string; last: string; hashFnv1a32: string }>;
}>;

export type PirateCatalogMedianRow = Readonly<{
  pirateShipId: string;
  name: string;
  sourceId: string;
  sourceStats: Readonly<Record<CombatFactionId, { population: number; attack: number; life: number; armor: number; weapon: string; armorType: string }>>;
  median: { population: number; attack: number; life: number; armor: number; weapon: string; armorType: string; attackPerPopulation: number; lifePerPopulation: number };
}>;

export type PirateLevelStats = Readonly<{
  shipId: string;
  name: string;
  level: 0 | 5 | 10;
  technologyLevel: number;
  attackPerUnit: number;
  lifePerUnit: number;
  armorPercent: number;
  ability: PirateShipDefinition['ability'];
}>;

function median(values: readonly number[]) {
  const sorted = [...values].sort((left, right) => left - right);
  const middle = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[middle]! : (sorted[middle - 1]! + sorted[middle]!) / 2;
}

function medianString(values: readonly string[]) {
  const counts = new Map<string, number>();
  values.forEach((value) => counts.set(value, (counts.get(value) ?? 0) + 1));
  return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0]![0];
}

function fnv1a32(value: string) {
  let hash = 0x811c9dc5;
  for (let i = 0; i < value.length; i += 1) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

function fnvAppend(state: number, value: string) {
  let hash = state;
  for (let i = 0; i < value.length; i += 1) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

function wilson(successes: number, total: number): readonly [number, number] {
  if (total <= 0) return [0, 1];
  const p = successes / total;
  const z2 = Z95 * Z95;
  const denominator = 1 + z2 / total;
  const center = (p + z2 / (2 * total)) / denominator;
  const half = Z95 * Math.sqrt((p * (1 - p) / total) + z2 / (4 * total * total)) / denominator;
  return [Math.max(0, center - half), Math.min(1, center + half)];
}

function seedFor(key: string, index: number) {
  return `${PIRATE_BALANCE_SEED_CORPUS.prefix}:${fnv1a32(key)}:${String(index).padStart(4, '0')}`;
}

function sourceEntity(faction: CombatFactionId, id: string) {
  const entity = getFactionShipCatalog(faction).find((candidate) => candidate.id === id);
  if (!entity) throw new Error(`No ${id} source ship for ${faction}`);
  return entity;
}

function catalogMedians(): PirateCatalogMedianRow[] {
  return PIRATE_BASE_SHIPS.map((pirate) => {
    const sourceStats = Object.fromEntries(FACTIONS.map((faction) => {
      const entity = sourceEntity(faction, pirate.sourceId);
      return [faction, {
        population: entity.population,
        attack: entity.combat.attack,
        life: entity.combat.life,
        armor: entity.combat.armorStrength,
        weapon: entity.combat.weaponType,
        armorType: entity.combat.armorType,
      }];
    })) as PirateCatalogMedianRow['sourceStats'];
    const stats = Object.values(sourceStats);
    const population = median(stats.map((entry) => entry.population));
    const attack = median(stats.map((entry) => entry.attack));
    const life = median(stats.map((entry) => entry.life));
    const armor = median(stats.map((entry) => entry.armor));
    return {
      pirateShipId: pirate.id as PirateBaseShipId,
      name: pirate.name,
      sourceId: pirate.sourceId,
      sourceStats,
      median: {
        population,
        attack,
        life,
        armor,
        weapon: medianString(stats.map((entry) => entry.weapon)),
        armorType: medianString(stats.map((entry) => entry.armorType)),
        attackPerPopulation: attack / population,
        lifePerPopulation: life / population,
      },
    };
  });
}

function sourceAbilityRows(): PirateSourceAbilityRow[] {
  const fixture = pirateAbilitySourceFixture as unknown as {
    ships: Array<{
      factionId: CombatFactionId;
      slotId: string;
      abilities: Array<{
        abilityClass: string;
        sourceMetrics: Array<{ sourceLabel: string; sourceValue: string; valuePercent?: string }>;
      }>;
    }>;
  };
  return PIRATE_BASE_SHIPS.map((pirate) => {
    const byFaction = Object.fromEntries(FACTIONS.map((faction) => {
      const source = fixture.ships.find((row) => row.factionId === faction && row.slotId === pirate.sourceId);
      if (!source) throw new Error(`No pinned source ability for ${faction}/${pirate.sourceId}`);
      return [faction, source.abilities];
    })) as Record<CombatFactionId, typeof fixture.ships[number]['abilities']>;
    const sourceByFaction = Object.fromEntries(FACTIONS.map((faction) => [
      faction,
      byFaction[faction].map((ability) => `${ability.abilityClass}: ${ability.sourceMetrics.map((metric) => `${metric.sourceLabel} ${metric.sourceValue}`).join(', ')}`).join('; '),
    ])) as Record<CombatFactionId, string>;
    const commonKeys = new Set(byFaction.aegis.flatMap((ability) => ability.sourceMetrics.map((metric) => `${ability.abilityClass}\u0000${metric.sourceLabel}`)));
    const commonAbilityMetricMedians = [...commonKeys].flatMap((key) => {
      const [abilityClass, metricLabel] = key.split('\u0000');
      const matched = Object.fromEntries(FACTIONS.map((faction) => {
        const metric = byFaction[faction].find((ability) => ability.abilityClass === abilityClass)?.sourceMetrics.find((candidate) => candidate.sourceLabel === metricLabel);
        return [faction, metric];
      })) as Record<CombatFactionId, { sourceValue: string; valuePercent?: string } | undefined>;
      if (FACTIONS.some((faction) => !matched[faction]?.valuePercent)) return [];
      const values = Object.fromEntries(FACTIONS.map((faction) => [faction, Number(matched[faction]!.valuePercent)])) as Record<CombatFactionId, number>;
      return [Object.freeze({
        abilityClass: abilityClass!,
        metricLabel: metricLabel!,
        factionValues: Object.freeze(Object.fromEntries(FACTIONS.map((faction) => [faction, matched[faction]!.sourceValue])) as Record<CombatFactionId, string>),
        medianSourcePercent: median(Object.values(values)),
      })];
    });
    return Object.freeze({
      pirateShipId: pirate.id as PirateBaseShipId,
      sourceId: pirate.sourceId,
      sourceByFaction: Object.freeze(sourceByFaction),
      commonAbilityMetricMedians: Object.freeze(commonAbilityMetricMedians),
    });
  });
}

function profileFor(band: typeof PIRATE_BALANCE_SCORE_BANDS[number], ship: PirateShipDefinition, suffix: string): PirateProfile {
  const profile = createPirateProfile({
    ownerId: `pirate-balance:${band.id}`,
    contactCycleKey: `balance/${band.id}/${suffix}`,
    score: { resourcePoints: band.resourcePoints, battlePoints: band.battlePoints, totalPoints: band.totalPoints },
  });
  if (ship.tier === 'special') throw new Error('Planet breaker is not an elimination profile');
  const shares = Object.freeze(Object.fromEntries(PIRATE_BASE_SHIPS.map((candidate) => [candidate.id, candidate.id === ship.id ? 100 : 0])) as Record<PirateBaseShipId, number>);
  return Object.freeze({ ...profile, tier: ship.tier, shares: Object.freeze({ ...shares, 'pirate-planet-breaker': 0 }) });
}

function allocateEntities(target: number, entities: readonly Readonly<{ id: string; population: number }>[], weights?: readonly number[]): CombatStackInput[] {
  const desiredWeights = weights ?? entities.map(() => 1 / entities.length);
  const totalWeight = desiredWeights.reduce((sum, value) => sum + value, 0);
  let counts = entities.map((entity, i) => Math.max(1, Math.floor(target * desiredWeights[i]! / totalWeight / entity.population)));
  let actual = counts.reduce((sum, count, i) => sum + count * entities[i]!.population, 0);
  // Correct the floor error while keeping the population split as even as possible.
  for (let step = 0; step < 10_000 && actual !== target; step += 1) {
    if (actual < target) {
      const choices = entities.map((entity, i) => ({ i, next: actual + entity.population, currentShare: counts[i]! * entity.population / target }))
        .filter((choice) => choice.next <= target)
        .sort((a, b) => a.currentShare - b.currentShare || a.i - b.i);
      const choice = choices[0];
      if (!choice) break;
      counts[choice.i]! += 1;
      actual += entities[choice.i]!.population;
    } else {
      const choices = entities.map((entity, i) => ({ i, next: actual - entity.population, currentShare: counts[i]! * entity.population / target }))
        .filter((choice) => counts[choice.i]! > 1 && choice.next >= 0)
        .sort((a, b) => a.currentShare - b.currentShare || a.i - b.i);
      const choice = choices[0];
      if (!choice) break;
      counts[choice.i]! -= 1;
      actual -= entities[choice.i]!.population;
    }
  }
  if (actual !== target) {
    // Search the nearest exact representable target below the request; fail rather than report unequal sides.
    for (let candidate = target - 1; candidate > target - 100; candidate -= 1) {
      const candidateCounts = entities.map((entity, i) => Math.max(1, Math.floor(candidate * desiredWeights[i]! / totalWeight / entity.population)));
      let candidatePopulation = candidateCounts.reduce((sum, count, i) => sum + count * entities[i]!.population, 0);
      for (let step = 0; step < 10_000 && candidatePopulation !== candidate; step += 1) {
        const choices = entities.map((entity, i) => ({ i, next: candidatePopulation + entity.population, currentShare: candidateCounts[i]! * entity.population / candidate }))
          .filter((choice) => choice.next <= candidate)
          .sort((a, b) => a.currentShare - b.currentShare || a.i - b.i);
        const choice = choices[0];
        if (!choice) break;
        candidateCounts[choice.i]! += 1;
        candidatePopulation += entities[choice.i]!.population;
      }
      if (candidatePopulation === candidate) { counts = candidateCounts; actual = candidate; break; }
    }
  }
  if (actual !== counts.reduce((sum, count, i) => sum + count * entities[i]!.population, 0)) throw new Error('Population allocation consistency error');
  return entities.map((entity, i) => ({ entityId: entity.id as CombatStackInput['entityId'], count: counts[i]!, level: 0 }));
}

function allocate(target: number, ids: readonly string[], faction: CombatFactionId, weights?: readonly number[]): CombatStackInput[] {
  return allocateEntities(target, ids.map((id) => sourceEntity(faction, id)), weights);
}

function allocateDefenses(target: number, ids: readonly string[], faction: CombatFactionId, weights?: readonly number[]): CombatStackInput[] {
  const entities = ids.map((id) => {
    const entity = getFactionDefenseCatalog(faction).find((candidate) => candidate.id === id);
    if (!entity) throw new Error(`No ${id} defense for ${faction}`);
    return entity;
  });
  return allocateEntities(target, entities, weights);
}

function populationOf(faction: CombatFactionId, stacks: readonly CombatStackInput[]) {
  return stacks.reduce((sum, stack) => {
    const entity = sourceEntity(faction, stack.entityId);
    return sum + stack.count * entity.population;
  }, 0);
}

function defensePopulationOf(faction: CombatFactionId, stacks: readonly CombatStackInput[]) {
  return stacks.reduce((sum, stack) => {
    const entity = getFactionDefenseCatalog(faction).find((candidate) => candidate.id === stack.entityId);
    if (!entity) throw new Error(`No ${stack.entityId} defense for ${faction}`);
    return sum + stack.count * entity.population;
  }, 0);
}

function winningCounter(pirateClass: typeof ORDINARY_CLASSES[number]) {
  return ORDINARY_CLASSES.map((playerClass) => ({ playerClass, multiplier: MATCHUP[playerClass][pirateClass] }))
    .sort((a, b) => b.multiplier - a.multiplier || ORDINARY_CLASSES.indexOf(a.playerClass) - ORDINARY_CLASSES.indexOf(b.playerClass))[0]!.playerClass;
}

function playerComposition(faction: CombatFactionId, playerClasses: readonly typeof ORDINARY_CLASSES[number][], target = FLEET_POPULATION): CombatStackInput[] {
  return allocate(target, playerClasses, faction);
}

function playerTech(level: number) {
  const tech = createDefaultCombatTechnologies();
  for (const id of Object.keys(tech) as (keyof typeof tech)[]) {
    tech[id] = id === 'piercingAttack' || id === 'maneuverDefense' ? 0 : level;
  }
  return tech;
}

function inputForElimination(
  band: typeof PIRATE_BALANCE_SCORE_BANDS[number],
  faction: CombatFactionId,
  ship: PirateShipDefinition,
  formation: PirateBalanceMatchup['formation'],
  playerClasses: readonly typeof ORDINARY_CLASSES[number][],
  attackerTechnologyLevel: PirateBalanceMatchup['attackerTechnologyLevel'],
  seed: string,
): { input: CombatInput; sentPopulation: number; piratePopulation: number } {
  const profile = profileFor(band, ship, `${faction}/${formation}/${playerClasses.join('+')}`);
  const playerShips = playerComposition(faction, playerClasses);
  const sentPopulation = playerShips.reduce((sum, stack) => sum + stack.count * sourceEntity(faction, stack.entityId).population, 0);
  const budget = calculatePirateEliminationPopulationBudget(sentPopulation, profile.shares);
  const piratePopulation = budget.actualPopulation;
  const priority = createDefaultCombatPriority();
  return {
    input: {
      scenarioId: `pirate-balance:${band.id}:${faction}:${ship.id}:${formation}:${playerClasses.join('+')}`,
      timestamp: '2026-10-04T00:00:00.000Z',
      attacker: {
        participant: { playerId: `balance-${faction}`, playerName: faction, race: faction, side: 'attacker' },
        factionId: faction,
        ships: playerShips,
        commanders: [],
      },
      defender: {
        participant: { playerId: 'balance-pirates', playerName: 'Пираты', race: 'pirates', side: 'defender' },
        combatProfile: { kind: 'pirate', snapshot: profile },
        ships: [{ entityId: ship.id, count: budget.ships[ship.id]!, level: profile.shipLevel }],
        commanders: [],
      },
      maxRounds: MAX_ROUNDS,
      attackerPriority: priority.attack,
      defenderPriority: priority.defense,
      attackerTechnologies: playerTech(attackerTechnologyLevel),
      technologyMode: 'independent',
      executionMode: 'production',
      seed,
    },
    sentPopulation,
    piratePopulation,
  };
}

function forceEndPopulation(report: BattleReport, side: 'attacker' | 'defender') {
  return side === 'attacker' ? report.attackerForce.populationAfter : report.defenderForce.populationAfter;
}

function runMatchup(
  band: typeof PIRATE_BALANCE_SCORE_BANDS[number],
  faction: CombatFactionId,
  ship: PirateShipDefinition,
  formation: PirateBalanceMatchup['formation'],
  playerClasses: readonly typeof ORDINARY_CLASSES[number][],
  attackerTechnologyLevel: PirateBalanceMatchup['attackerTechnologyLevel'],
  runs: number,
): PirateBalanceMatchup {
  const matchupKey = JSON.stringify(['elimination', band.id, faction, ship.id, formation, playerClasses, attackerTechnologyLevel]);
  const winnerCounts: Record<BattleWinner, number> = { attacker: 0, defender: 0, draw: 0 };
  const attackerResiduals: number[] = [];
  const defenderResiduals: number[] = [];
  let totalRounds = 0;
  let hash = 0x811c9dc5;
  let first = '';
  let last = '';
  let attackerPopulation = 0;
  let defenderPopulation = 0;
  let pirateTargetPopulation = 0;
  for (let index = 0; index < runs; index += 1) {
    const seed = seedFor(matchupKey, index);
    first ||= seed;
    last = seed;
    hash = fnvAppend(hash, `${seed}\n`);
    const scenario = inputForElimination(band, faction, ship, formation, playerClasses, attackerTechnologyLevel, seed);
    attackerPopulation = scenario.sentPopulation;
    defenderPopulation = scenario.piratePopulation;
    pirateTargetPopulation = Math.round(scenario.sentPopulation * 0.9);
    const report = resolveCombat(scenario.input, { reportId: `balance:${fnv1a32(matchupKey)}:${index}`, missionType: 'pirate-elimination' });
    winnerCounts[report.winner] += 1;
    attackerResiduals.push(forceEndPopulation(report, 'attacker'));
    defenderResiduals.push(forceEndPopulation(report, 'defender'));
    totalRounds += report.roundCount;
  }
  const wins = winnerCounts.attacker;
  const draws = winnerCounts.draw;
  const losses = winnerCounts.defender;
  const summarize = (values: number[]) => [median(values), Math.min(...values), Math.max(...values)] as const;
  const attackerStats = summarize(attackerResiduals);
  const defenderStats = summarize(defenderResiduals);
  return Object.freeze({
    key: matchupKey,
    scoreBand: band.id,
    totalPoints: band.totalPoints,
    pirateLevel: pirateLevelForResourcePoints(band.resourcePoints),
    attackerTechnologyLevel,
    faction,
    pirateShipId: ship.id as PirateBaseShipId,
    formation,
    playerClasses: Object.freeze([...playerClasses]),
    counterClass: winningCounter(ship.ordinaryClass as typeof ORDINARY_CLASSES[number]),
    requestedPopulation: attackerPopulation,
    attackerActualPopulation: attackerPopulation,
    pirateTargetPopulation,
    piratePopulationError: Math.abs(defenderPopulation - pirateTargetPopulation),
    defenderActualPopulation: defenderPopulation,
    runs,
    winnerCounts: Object.freeze(winnerCounts),
    attackerWinRate: wins / runs,
    attackerWinRate95: wilson(wins, runs),
    drawRate: draws / runs,
    drawRate95: wilson(draws, runs),
    defenderWinRate: losses / runs,
    defenderWinRate95: wilson(losses, runs),
    attackerResidualMedian: attackerStats[0],
    attackerResidualRange: [attackerStats[1], attackerStats[2]] as const,
    defenderResidualMedian: defenderStats[0],
    defenderResidualRange: [defenderStats[1], defenderStats[2]] as const,
    meanRounds: totalRounds / runs,
    seedCorpus: Object.freeze({ first, last, hashFnv1a32: (hash >>> 0).toString(16).padStart(8, '0') }),
  });
}

function pirateLevelStats(): PirateLevelStats[] {
  const levels: readonly [0 | 5 | 10, number][] = [[0, 1_000], [5, 100_000], [10, 10_000_000]];
  return PIRATE_BASE_SHIPS.flatMap((ship) => levels.map(([level, points]) => {
    const band = PIRATE_BALANCE_SCORE_BANDS.find((candidate) => candidate.resourcePoints === points)!;
    const profile = profileFor(band, ship, `stat/${level}`);
    const priority = createDefaultCombatPriority();
    const targetClass = ship.ordinaryClass === 'planet-breaker' ? 'death-star' : ship.ordinaryClass;
    const input: CombatInput = {
      scenarioId: `pirate-stat:${ship.id}:${level}`,
      timestamp: '2026-10-04T00:00:00.000Z',
      attacker: {
        participant: { playerId: 'pirate-stat', playerName: 'Пираты', race: 'pirates', side: 'attacker' },
        combatProfile: { kind: 'pirate', snapshot: profile },
        ships: [{ entityId: ship.id, count: 1, level }], commanders: [],
      },
      defender: {
        participant: { playerId: 'stat-target', playerName: 'Цель', race: 'aegis', side: 'defender' },
        factionId: 'aegis',
        ships: [{ entityId: targetClass === 'death-star' ? 'scout' : 'scout', count: 1 }], commanders: [], defenses: [],
      },
      maxRounds: MAX_ROUNDS,
      attackerPriority: priority.attack,
      defenderPriority: priority.defense,
      seed: `pirate-stat:${ship.id}:${level}`,
    };
    const report = resolveCombat(input, { reportId: `pirate-stat:${ship.id}:${level}`, missionType: 'pirate-raid' });
    const stack = report.initialSnapshot?.attacker.stacks.find((candidate) => candidate.entityId === ship.id);
    return Object.freeze({
      shipId: ship.id,
      name: ship.name,
      level,
      technologyLevel: profile.technologyLevel,
      attackPerUnit: stack?.attackPerUnit ?? 0,
      lifePerUnit: stack?.lifePerUnit ?? 0,
      armorPercent: stack?.armor ?? 0,
      ability: ship.ability,
    });
  }));
}

function raidEstimates(owners = 1_000): PirateBalanceRaidEstimate[] {
  const horizons = [24, 72] as const;
  const systemCounts = [1, 2, 3, 5] as const;
  const qValues = [0, 0.5, 2 / 3, 10 / 11, 1] as const;
  const epoch = Date.UTC(2026, 0, 1);
  const ratiosToPoints = (q: number) => q === 0
    ? [0, 1_000_000] as const
    : q === 0.5
      ? [1_000_000, 1_000_000] as const
      : Math.abs(q - 2 / 3) < 1e-9
        ? [1_000_000, 500_000] as const
        : Math.abs(q - 10 / 11) < 1e-9
          ? [1_000_000, 100_000] as const
          : [1_000_000, 0] as const;
  return qValues.flatMap((q) => horizons.flatMap((horizonHours) => systemCounts.map((independentSystems) => {
    const endAt = epoch + horizonHours * 60 * 60 * 1_000;
    let contactsProcessed = 0;
    let expectedContactsTotal = 0;
    let raidsTotal = 0;
    const raidCounts: number[] = [];
    const systemRaidCounts = Array<number>(owners * independentSystems).fill(0);
    let seedHash = 0x811c9dc5;
    let firstSeed = '';
    let lastSeed = '';
    const [resourcePoints, battlePoints] = ratiosToPoints(q);
    for (let ownerIndex = 0; ownerIndex < owners; ownerIndex += 1) {
      const ownerId = `balance-owner-${String(ownerIndex).padStart(4, '0')}`;
      let raids = 0;
      let contacts = 0;
      for (let system = 1; system <= independentSystems; system += 1) {
        for (let cycleIndex = 0; ; cycleIndex += 1) {
          const schedule = getUniverseTimedObjectSchedule('pirate', 1, system, cycleIndex);
          if (!schedule || schedule.startAt >= endAt) break;
          if (!schedule.present || schedule.startAt + 15 * 60 * 1_000 >= endAt) continue;
          contacts += 1;
          const seedIdentity = JSON.stringify(['pirate-raid:v1', ownerId, pirateContactCycleKey(1, system, cycleIndex)]);
          firstSeed ||= seedIdentity;
          lastSeed = seedIdentity;
          seedHash = fnvAppend(seedHash, `${seedIdentity}\n`);
          const outcome = resolvePirateRaidCycle({ ownerId, galaxy: 1, system, cycleIndex, resourcePoints, battlePoints, colonyIds: [`owner-${ownerIndex}-system-${system}-colony`] });
          if (outcome.rollSucceeded) {
            raids += 1;
            systemRaidCounts[ownerIndex * independentSystems + system - 1]! += 1;
          }
        }
      }
      contactsProcessed += contacts;
      expectedContactsTotal += contacts;
      raidsTotal += raids;
      raidCounts.push(raids);
    }
    const zero = raidCounts.filter((count) => count === 0).length;
    const one = raidCounts.filter((count) => count === 1).length;
    const multiple = raidCounts.filter((count) => count > 1).length;
    const systemsWithZero = systemRaidCounts.filter((count) => count === 0).length;
    const systemsWithOne = systemRaidCounts.filter((count) => count === 1).length;
    const systemsWithMultiple = systemRaidCounts.filter((count) => count > 1).length;
    const chancePerContact = pirateRaidChance(calculatePirateActivityRatio(resourcePoints, battlePoints));
    return Object.freeze({
      q,
      chancePerContact,
      horizonHours,
      independentSystems,
      owners,
      contactsProcessed,
      expectedContactsPerOwner: expectedContactsTotal / owners,
      raidRatePerSystem: raidsTotal / (owners * independentSystems),
      systemsWithZeroRate: systemsWithZero / systemRaidCounts.length,
      systemsWithOneRate: systemsWithOne / systemRaidCounts.length,
      systemsWithMultipleRate: systemsWithMultiple / systemRaidCounts.length,
      systemsWithAtLeastOneRate95: wilson(systemRaidCounts.length - systemsWithZero, systemRaidCounts.length),
      raidRatePerOwner: raidsTotal / owners,
      ownersWithZeroRaids: zero,
      ownersWithOneRaid: one,
      ownersWithMultipleRaids: multiple,
      ownersWithZeroRate: zero / owners,
      ownersWithOneRate: one / owners,
      ownersWithMultipleRate: multiple / owners,
      ownersWithAtLeastOneRate95: wilson(owners - zero, owners),
      raidCountRange: [Math.min(...raidCounts), Math.max(...raidCounts)] as const,
      aggregateIndependentSystemProbability: aggregatePirateRaidChance(chancePerContact, independentSystems),
      seedCorpus: Object.freeze({ first: firstSeed, last: lastSeed, hashFnv1a32: (seedHash >>> 0).toString(16).padStart(8, '0') }),
    });
  })));
}

function exactPopulation(stacks: readonly CombatStackInput[], faction: CombatFactionId, kind: 'fleet' | 'defense') {
  return kind === 'fleet' ? populationOf(faction, stacks) : defensePopulationOf(faction, stacks);
}

function allocateExact(target: number, faction: CombatFactionId, kind: 'fleet' | 'defense', ids: readonly string[], weights?: readonly number[]) {
  const entities = kind === 'fleet'
    ? ids.map((id) => sourceEntity(faction, id))
    : ids.map((id) => {
      const entity = getFactionDefenseCatalog(faction).find((candidate) => candidate.id === id);
      if (!entity) throw new Error(`No ${id} defense for ${faction}`);
      return entity;
    });
  const desiredWeights = weights ?? entities.map(() => 1 / entities.length);
  const weightTotal = desiredWeights.reduce((sum, value) => sum + value, 0);
  let counts: number[];
  if (entities.length === 1) {
    if (target % entities[0]!.population !== 0) throw new Error(`Population ${target} is not representable by ${entities[0]!.id}`);
    counts = [target / entities[0]!.population];
  } else if (entities.length === 2) {
    let bestCounts: number[] | undefined;
    let bestCost = Number.POSITIVE_INFINITY;
    for (let firstCount = 1; firstCount * entities[0]!.population < target; firstCount += 1) {
      const remainder = target - firstCount * entities[0]!.population;
      if (remainder % entities[1]!.population !== 0) continue;
      const secondCount = remainder / entities[1]!.population;
      if (secondCount < 1) continue;
      const firstShare = firstCount * entities[0]!.population;
      const secondShare = secondCount * entities[1]!.population;
      const cost = Math.abs(firstShare - target * desiredWeights[0]! / weightTotal)
        + Math.abs(secondShare - target * desiredWeights[1]! / weightTotal);
      if (cost < bestCost) { bestCounts = [firstCount, secondCount]; bestCost = cost; }
    }
    if (!bestCounts) throw new Error(`Population ${target} is not representable using ${ids.join('+')}`);
    counts = bestCounts;
  } else {
    const candidate = kind === 'fleet' ? allocate(target, ids, faction, weights) : allocateDefenses(target, ids, faction, weights);
    counts = candidate.map((stack) => stack.count);
  }
  const stacks = entities.map((entity, index) => ({ entityId: entity.id as CombatStackInput['entityId'], count: counts[index]!, level: 0 }));
  const actual = exactPopulation(stacks, faction, kind);
  if (actual !== target) throw new Error(`Cannot build exact ${kind} defender population ${target} for ${faction}; got ${actual}`);
  return stacks;
}

function siegeDefenders(faction: CombatFactionId, composition: PirateBalanceSiegeEstimate['defenderComposition'], target: PirateBalanceSiegeEstimate['defenderPopulation']) {
  if (composition === 'empty') return { ships: [] as CombatStackInput[], defenses: [] as CombatStackInput[] };
  if (composition === 'fleet-only') {
    const ships = allocateExact(target, faction, 'fleet', ['scout', 'cruiser'], [0.65, 0.35]);
    return { ships, defenses: [] as CombatStackInput[] };
  }
  if (composition === 'defense-only') {
    const defenses = allocateExact(target, faction, 'defense', ['ballistic-turret', 'laser-turret'], [0.65, 0.35]);
    return { ships: [] as CombatStackInput[], defenses };
  }

  // Find a nearly even split whose ship and defense rosters each represent their exact snapshot population.
  const midpoint = Math.floor(target / 2);
  for (let offset = 0; offset <= target; offset += 1) {
    const candidates = offset === 0 ? [midpoint] : [midpoint - offset, midpoint + offset];
    for (const fleetPopulation of candidates) {
      const defensePopulation = target - fleetPopulation;
      if (fleetPopulation < 1 || defensePopulation < 1) continue;
      try {
        const ships = allocateExact(fleetPopulation, faction, 'fleet', ['scout', 'cruiser'], [0.65, 0.35]);
        const defenses = allocateExact(defensePopulation, faction, 'defense', ['ballistic-turret', 'laser-turret'], [0.65, 0.35]);
        return { ships, defenses };
      } catch {
        // Try the adjacent split; the report still records exactly the target total.
      }
    }
  }
  throw new Error(`Cannot build exact mixed defender population ${target} for ${faction}`);
}

function nearestPirateUnitCount(populationBudget: number, ship: PirateShipDefinition) {
  const lowerCount = Math.floor(populationBudget / ship.population);
  const upperCount = lowerCount + (populationBudget % ship.population === 0 ? 0 : 1);
  const lowerError = Math.abs(populationBudget - lowerCount * ship.population);
  const upperError = Math.abs(upperCount * ship.population - populationBudget);
  return Math.max(1, lowerError <= upperError ? lowerCount : upperCount);
}

function runSiegeEstimate(
  faction: CombatFactionId,
  defenderComposition: PirateBalanceSiegeEstimate['defenderComposition'],
  defenderPopulation: PirateBalanceSiegeEstimate['defenderPopulation'],
  ship: PirateShipDefinition,
  runs: number,
): PirateBalanceSiegeEstimate {
  const totalPoints = 10_000_000;
  const band = PIRATE_BALANCE_SCORE_BANDS.find((candidate) => candidate.totalPoints === totalPoints)!;
  const profile = profileFor(band, ship, `siege/${faction}/${defenderComposition}/${defenderPopulation}`);
  const pri = createDefaultCombatPriority();
  let hash = 0x811c9dc5;
  let first = '';
  let last = '';
  let wins = 0;
  let defenderWins = 0;
  let draws = 0;
  let losses = 0;
  let breakerAppearances = 0;
  const attackerResiduals: number[] = [];
  const defenderResiduals: number[] = [];
  const defenders = siegeDefenders(faction, defenderComposition, defenderPopulation);
  const actualDefenderPopulation = populationOf(faction, defenders.ships) + defensePopulationOf(faction, defenders.defenses);
  if (actualDefenderPopulation !== defenderPopulation) throw new Error(`Defender target mismatch: requested ${defenderPopulation}, built ${actualDefenderPopulation}`);
  const raidBudget = Math.round(defenderPopulation * pirateRaidPopulationMultiplier(1));
  const normalShipCount = nearestPirateUnitCount(raidBudget, ship);
  const normalPopulation = normalShipCount * ship.population;
  const breakerEligible = canUsePiratePlanetBreaker(totalPoints, defenderPopulation);
  for (let index = 0; index < runs; index += 1) {
    const seed = seedFor(JSON.stringify(['siege', faction, defenderComposition, defenderPopulation, ship.id, totalPoints]), index);
    first ||= seed;
    last = seed;
    hash = fnvAppend(hash, `${seed}\n`);
    const ownerId = `pirate-balance-siege:${faction}:${defenderComposition}:${defenderPopulation}:${String(index).padStart(4, '0')}`;
    const contactCycleKey = `balance-siege/${faction}/${defenderComposition}/${defenderPopulation}/${index}`;
    const targetPlanetId = `siege-target-${faction}-${defenderComposition}-${defenderPopulation}`;
    const breakerSeed = JSON.stringify(['pirate-planet-breaker:v1', ownerId, contactCycleKey, targetPlanetId]);
    const breakerRoll = createSeededCombatRng(breakerSeed).next();
    const hasBreaker = breakerEligible && breakerRoll < PIRATE_PLANET_BREAKER_APPEARANCE_CHANCE;
    if (hasBreaker) breakerAppearances += 1;
    const input: CombatInput = {
      scenarioId: `pirate-siege:${faction}:${defenderComposition}:${defenderPopulation}:${ship.id}`,
      timestamp: '2026-10-04T00:00:00.000Z',
      attacker: {
        participant: { playerId: 'pirates', playerName: 'Пираты', race: 'pirates', side: 'attacker' },
        combatProfile: { kind: 'pirate', snapshot: profile },
        ships: [
          { entityId: ship.id, count: normalShipCount, level: profile.shipLevel },
          ...(hasBreaker ? [{ entityId: 'pirate-planet-breaker' as const, count: 1, level: profile.shipLevel }] : []),
        ], commanders: [],
      },
      defender: {
        participant: { playerId: `target-${faction}`, playerName: faction, race: faction, side: 'defender' },
        factionId: faction,
        ships: defenders.ships,
        commanders: [],
        defenses: defenders.defenses,
      },
      maxRounds: MAX_ROUNDS,
      attackerPriority: pri.attack,
      defenderPriority: pri.defense,
      seed,
    };
    const report = resolveCombat(input, { reportId: `pirate-siege:${faction}:${defenderComposition}:${defenderPopulation}:${ship.id}:${index}`, missionType: 'pirate-raid' });
    if (report.defenderForce.populationBefore !== defenderPopulation) throw new Error(`Combat snapshot population ${report.defenderForce.populationBefore} did not match ${defenderPopulation}`);
    if (report.winner === 'attacker') wins += 1;
    if (report.winner === 'defender') defenderWins += 1;
    if (report.winner === 'draw') draws += 1;
    attackerResiduals.push(report.attackerForce.populationAfter);
    defenderResiduals.push(report.defenderForce.populationAfter);
    const siege = resolvePlanetSiege(report, {
      id: targetPlanetId,
      name: 'Target',
      coordinate: { galaxy: 1, system: 1, position: 3 },
      buildings: { 'metal-mine': 10 },
    }, {
      seed,
      reportId: report.id,
      attackerFleetId: `fleet:${index}`,
      attackerFactionId: 'aegis',
      defenderFactionId: faction,
      targetOwnerPlanetCount: 2,
      targetOwnerTotalPoints: totalPoints,
    });
    if (siege.planetDestroyed) losses += 1;
  }
  const summarize = (values: number[]) => [median(values), Math.min(...values), Math.max(...values)] as const;
  const attackerStats = summarize(attackerResiduals);
  const defenderStats = summarize(defenderResiduals);
  return Object.freeze({
    defenderFaction: faction,
    defenderComposition,
    defenderPopulation,
    pirateShipId: ship.id as PirateBaseShipId,
    ownerTotalPoints: totalPoints,
    breakerEligible,
    runs,
    breakerAppearances,
    breakerAppearanceRate: breakerAppearances / runs,
    breakerAppearanceRate95: wilson(breakerAppearances, runs),
    battleWins: wins,
    battleWinRate: wins / runs,
    battleWinRate95: wilson(wins, runs),
    defenderWins,
    defenderWinRate: defenderWins / runs,
    defenderWinRate95: wilson(defenderWins, runs),
    draws,
    drawRate: draws / runs,
    drawRate95: wilson(draws, runs),
    attackerResidualMedian: attackerStats[0],
    attackerResidualRange: [attackerStats[1], attackerStats[2]] as const,
    defenderResidualMedian: defenderStats[0],
    defenderResidualRange: [defenderStats[1], defenderStats[2]] as const,
    planetLosses: losses,
    planetLossRate: losses / runs,
    planetLossRate95: wilson(losses, runs),
    seedCorpus: Object.freeze({ first, last, hashFnv1a32: (hash >>> 0).toString(16).padStart(8, '0') }),
  });
}

function budgetCheck() {
  const sentCombatPopulation = 10_000;
  return Object.freeze({
    sentCombatPopulation,
    requestedPopulation: Math.round(sentCombatPopulation * 0.9),
    cases: Object.freeze(PIRATE_BASE_SHIPS.map((ship) => {
      const shares = Object.freeze(Object.fromEntries(PIRATE_BASE_SHIPS.map((candidate) => [candidate.id, candidate.id === ship.id ? 100 : 0])));
      const budget = calculatePirateEliminationPopulationBudget(sentCombatPopulation, shares);
      return Object.freeze({
        shipId: ship.id as PirateBaseShipId,
        actualPopulation: budget.actualPopulation,
        absoluteError: budget.absoluteError,
        populationPerShip: ship.population,
        unitCount: budget.ships[ship.id] ?? 0,
      });
    })),
  });
}

function profileTierEstimates(runs = 10_000): PirateProfileTierEstimate[] {
  return PIRATE_BALANCE_SCORE_BANDS.map((band) => {
    const tierCounts: Record<1 | 2 | 3, number> = { 1: 0, 2: 0, 3: 0 };
    let hash = 0x811c9dc5;
    let first = '';
    let last = '';
    for (let index = 0; index < runs; index += 1) {
      const ownerId = `pirate-balance-profile:${band.id}:${String(index).padStart(5, '0')}`;
      const cycleKey = `profile/${band.id}/${String(index).padStart(5, '0')}`;
      const profile = createPirateProfile({
        ownerId,
        contactCycleKey: cycleKey,
        score: { resourcePoints: band.resourcePoints, battlePoints: band.battlePoints, totalPoints: band.totalPoints },
      });
      first ||= profile.seed;
      last = profile.seed;
      hash = fnvAppend(hash, `${profile.seed}\n`);
      tierCounts[profile.tier] += 1;
    }
    return Object.freeze({
      totalPoints: band.totalPoints,
      resourcePoints: band.resourcePoints,
      runs,
      expectedShares: expectedPirateTierShares(band.totalPoints),
      observedShares: {
        1: tierCounts[1] / runs,
        2: tierCounts[2] / runs,
        3: tierCounts[3] / runs,
      },
      confidence95: {
        1: wilson(tierCounts[1], runs),
        2: wilson(tierCounts[2], runs),
        3: wilson(tierCounts[3], runs),
      },
      seedCorpus: Object.freeze({ first, last, hashFnv1a32: (hash >>> 0).toString(16).padStart(8, '0') }),
    });
  });
}

/** Runs seeded resolver comparisons for all unlocked pirate classes and the 24/72-hour schedule samples. */
export function runPirateBalanceSimulation(options: { runsPerMatchup?: number; ownersForRaidEstimates?: number } = {}): PirateBalanceSimulation {
  const runsPerMatchup = options.runsPerMatchup ?? 300;
  if (!Number.isSafeInteger(runsPerMatchup) || runsPerMatchup < 1) throw new RangeError('runsPerMatchup must be a positive safe integer');
  const matchups: PirateBalanceMatchup[] = [];
  for (const band of PIRATE_BALANCE_SCORE_BANDS) {
    const allowedTiers = new Set<1 | 2 | 3>(([1, 2, 3] as const)
      .filter((tier) => band.expectedTierShares[tier] > 0));
    const availableShips = PIRATE_BASE_SHIPS.filter((ship) => allowedTiers.has(ship.tier as 1 | 2 | 3));
    for (const faction of FACTIONS) {
      for (const ship of availableShips) {
        const counterClass = winningCounter(ship.ordinaryClass as typeof ORDINARY_CLASSES[number]);
        const playerFormats = [
          ...ORDINARY_CLASSES.map((playerClass) => ({
            formation: playerClass === ship.ordinaryClass ? 'mirror' as const : playerClass === counterClass ? 'counter' as const : 'single' as const,
            playerClasses: [playerClass] as const,
          })),
          ...ORDINARY_CLASSES.flatMap((first, index) => ORDINARY_CLASSES.slice(index + 1).map((second) => ({
            formation: 'pair' as const,
            playerClasses: [first, second] as const,
          }))),
          { formation: 'mixed' as const, playerClasses: ORDINARY_CLASSES },
        ];
        for (const { formation, playerClasses } of playerFormats) {
          for (const attackerTechnologyLevel of PIRATE_BALANCE_ATTACKER_TECH_BANDS) {
            matchups.push(runMatchup(band, faction, ship, formation, playerClasses, attackerTechnologyLevel, runsPerMatchup));
          }
        }
      }
    }
  }
  const siegeRuns = runsPerMatchup;
  const siegeCases: readonly Readonly<{ composition: PirateBalanceSiegeEstimate['defenderComposition']; population: PirateBalanceSiegeEstimate['defenderPopulation'] }>[] = [
    { composition: 'empty', population: 0 },
    ...(['fleet-only', 'defense-only', 'mixed'] as const).flatMap((composition) => ([1_999, 2_000] as const).map((population) => ({ composition, population }))),
  ];
  const siegeEstimates = FACTIONS.flatMap((faction) => siegeCases.flatMap(({ composition, population }) => (
    PIRATE_BASE_SHIPS.map((ship) => runSiegeEstimate(faction, composition, population, ship, siegeRuns))
  )));
  return Object.freeze({
    seedCorpus: PIRATE_BALANCE_SEED_CORPUS,
    runsPerMatchup,
    matchups: Object.freeze(matchups),
    profileTierEstimates: Object.freeze(profileTierEstimates()),
    raidEstimates: Object.freeze(raidEstimates(options.ownersForRaidEstimates ?? 1_000)),
    siegeEstimates: Object.freeze(siegeEstimates),
    catalogSourceMedians: Object.freeze(catalogMedians()),
    sourceAbilityRows: Object.freeze(sourceAbilityRows()),
    levelStats: Object.freeze(pirateLevelStats()),
    budgetCheck: budgetCheck(),
  });
}

function percentage(value: number) {
  return `${(value * 100).toFixed(1)}%`;
}

function comma(value: number) {
  return Math.round(value).toLocaleString('en-US');
}

function ci(interval: readonly [number, number]) {
  return `${percentage(interval[0])}–${percentage(interval[1])}`;
}

/** Markdown renderer used to create the evidence file from the returned run data. */
export function formatPirateBalanceEvidence(result: PirateBalanceSimulation, generatedAt = '2026-10-04'): string {
  const medianRows = result.catalogSourceMedians.map((row) => `| ${row.pirateShipId} (${row.name}) | ${row.sourceId} | ${row.median.population} | ${comma(row.median.attack)} | ${comma(row.median.life)} | ${row.median.armor}% | ${row.median.weapon} / ${row.median.armorType} | ${row.median.attackPerPopulation.toFixed(2)} / ${row.median.lifePerPopulation.toFixed(2)} |`).join('\n');
  const statsRows = result.levelStats.map((row) => `| ${row.shipId} · ур. ${row.level} | ${row.technologyLevel} | ${comma(row.attackPerUnit)} | ${comma(row.lifePerUnit)} | ${row.armorPercent.toFixed(2)}% | ${JSON.stringify(row.ability)} |`).join('\n');
  const budgetRows = result.budgetCheck.cases.map((row) => `| ${row.shipId} | ${row.populationPerShip} | ${row.unitCount} | ${row.actualPopulation} | ${row.absoluteError} |`).join('\n');
  const profileTierRows = result.profileTierEstimates.map((row) => `| ${comma(row.totalPoints)} | ${comma(row.resourcePoints)} | ${row.runs} | ${percentage(row.expectedShares[1] / 100)} / ${percentage(row.expectedShares[2] / 100)} / ${percentage(row.expectedShares[3] / 100)} | ${percentage(row.observedShares[1])} [${ci(row.confidence95[1])}] / ${percentage(row.observedShares[2])} [${ci(row.confidence95[2])}] / ${percentage(row.observedShares[3])} [${ci(row.confidence95[3])}] | \`${row.seedCorpus.hashFnv1a32}\` |`).join('\n');
  const sourceAbilityRows = result.sourceAbilityRows.map((row) => {
    const medians = row.commonAbilityMetricMedians.map((metric) => `${metric.abilityClass} / ${metric.metricLabel}: ${metric.factionValues.aegis}, ${metric.factionValues.synod}, ${metric.factionValues.veyra}; median ${metric.medianSourcePercent.toFixed(3)}%`).join('<br>');
    return `| ${row.pirateShipId} (${row.sourceId}) | ${row.sourceByFaction.aegis} | ${row.sourceByFaction.synod} | ${row.sourceByFaction.veyra} | ${medians || 'Нет общей способности и метрики у всех трёх источников'} |`;
  }).join('\n');
  const qControlRows = result.raidEstimates.filter((row) => row.horizonHours === 24 && row.independentSystems === 3).map((row) => `| ${row.q.toFixed(3)} | ${percentage(row.chancePerContact)} | ${percentage(pirateRaidPopulationMultiplier(row.q))} | ${percentage(row.aggregateIndependentSystemProbability)} |`).join('\n');
  const matchupRows = result.matchups.map((row) => `| ${row.scoreBand} (${comma(row.totalPoints)}) | ${row.pirateLevel} | ${row.attackerTechnologyLevel} | ${row.faction} | ${row.pirateShipId} | ${row.formation} (${row.playerClasses.join('+')}; counter ${row.counterClass}) | ${row.attackerActualPopulation} / ${row.pirateTargetPopulation} / ${row.defenderActualPopulation} (ошибка ${row.piratePopulationError}) | ${row.runs} | ${row.winnerCounts.attacker}/${row.winnerCounts.draw}/${row.winnerCounts.defender} | ${percentage(row.attackerWinRate)} [${ci(row.attackerWinRate95)}] | ${percentage(row.drawRate)} [${ci(row.drawRate95)}] | ${percentage(row.defenderWinRate)} [${ci(row.defenderWinRate95)}] | ${row.attackerResidualMedian} [${row.attackerResidualRange.join('–')}] / ${row.defenderResidualMedian} [${row.defenderResidualRange.join('–')}] | ${row.meanRounds.toFixed(2)} | \`${row.seedCorpus.hashFnv1a32}\` |`).join('\n');
  const raidRows = result.raidEstimates.map((row) => `| ${row.q.toFixed(3)} (${percentage(row.chancePerContact)}) | ${row.horizonHours} | ${row.independentSystems} | ${row.owners} | ${row.contactsProcessed} | ${row.expectedContactsPerOwner.toFixed(2)} | ${row.raidRatePerSystem.toFixed(3)} / ${row.raidRatePerOwner.toFixed(3)} | ${percentage(row.systemsWithZeroRate)} / ${percentage(row.systemsWithOneRate)} / ${percentage(row.systemsWithMultipleRate)} [P≥1 ${ci(row.systemsWithAtLeastOneRate95)}] | ${percentage(row.ownersWithZeroRate)} / ${percentage(row.ownersWithOneRate)} / ${percentage(row.ownersWithMultipleRate)} [P≥1 ${ci(row.ownersWithAtLeastOneRate95)}] | ${row.raidCountRange.join('–')} | ${percentage(row.aggregateIndependentSystemProbability)} | \`${row.seedCorpus.hashFnv1a32}\` |`).join('\n');
  const siegeRows = result.siegeEstimates.map((row) => `| ${row.defenderFaction} | ${row.defenderComposition} | ${row.defenderPopulation} | ${row.pirateShipId} | ${row.ownerTotalPoints} | ${row.breakerEligible ? 'да' : 'нет'} | ${row.breakerAppearances}/${row.runs} (${percentage(row.breakerAppearanceRate)}, 95% ${ci(row.breakerAppearanceRate95)}) | ${row.runs} | ${row.battleWins} (${percentage(row.battleWinRate)}, ${ci(row.battleWinRate95)}) / ${row.defenderWins} (${percentage(row.defenderWinRate)}, ${ci(row.defenderWinRate95)}) / ${row.draws} (${percentage(row.drawRate)}, ${ci(row.drawRate95)}) | ${row.attackerResidualMedian} [${row.attackerResidualRange.join('–')}] / ${row.defenderResidualMedian} [${row.defenderResidualRange.join('–')}] | ${row.planetLosses} (${percentage(row.planetLossRate)}, 95% Wilson ${ci(row.planetLossRate95)}) | \`${row.seedCorpus.hashFnv1a32}\` |`).join('\n');
  return `# Pirate Operations V1 — баланс-симуляции

Дата формирования: ${generatedAt}. Этот отчёт создаётся функцией \`formatPirateBalanceEvidence(runPirateBalanceSimulation())\` из текущих каталогов, профилей, расписания и production \`resolveCombat\`. Это проверка внутренней модели Asterion, а не доказательство Nemexia parity.

## Входные данные и модель

- Три игровые фракции: Aegis, Synod, Veyra; исходные характеристики извлекаются из \`getFactionShipCatalog\` в \`src/domain/combat/faction-catalog.ts\`.
- Шесть базовых NPC-классов. Погибель/planet-breaker исключён из elimination гарнизона; в рейдовой матрице он добавляется к обычному пиратскому составу в ${percentage(PIRATE_PLANET_BREAKER_APPEARANCE_CHANCE)} подходящих seeded роллов, не более одного.
- Пираты имеют по одному классу в профиле, 100% shares. Разрешённые тиры берутся из ненулевых expected weights текущего профиля: score 1,000 даёт только tier 1; к 10,000 открывается tier 2; к 100,000 доступны tier 1–3; к 1,000,000 tier 3 становится крупнейшей долей.
- Score bands: 1,000 / 10,000 / 100,000 / 1,000,000 / 10,000,000; score snapshot имеет battlePoints=0 и resourcePoints=totalPoints. До 10,000 seeded профилей на band сравнивают распределение с целевыми долями; уровни пиратов берутся из текущего score profile.
- Заданный combat population игрока — ${comma(FLEET_POPULATION)}. После сборки ростера фактический отправленный population пересчитывается; именно от него применяется округлённый 90%-ный pirate budget, а отчёт показывает цель, фактический roster и ошибку округления. Для уровней технологий 0/5/10 состав и точный фактический population совпадают. Игроку выставлен resolver-valid набор технологий с одной exclusive категорией Critical Hit; обе стороны используют production resolver на 8 раундов.
- Матчапы включают все шесть одиночных классов (включая mirror и лучший counter), все 15 пар разных классов и mixed флот из шести классов. Контр-класс — максимум коэффициента игрок→пират; при равенстве используется стабильный порядок каталога. Матрица коэффициентов соответствует текущей таблице resolver.
- Для каждого score-band × раса × доступный pirate class × formation × player tech matchup — ${result.runsPerMatchup} seeded outcomes с seed \`${PIRATE_BALANCE_SEED_CORPUS.prefix}:${'<scenario FNV-1a hex>'}:${'<index 0000..>'}\`. Win/draw intervals are 95% Wilson binomial intervals; residual population is median and observed min–max, not a confidence interval.

## Медианы источника для шести классов

Медиана берётся по трём текущим faction catalogs отдельно для каждого числового поля; строки/типы оружия и брони выбираются mode с bytewise-stable tie-break. Отношения — median attack/population и life/population.

| NPC ID / имя | Источник ID | Население | Атака | Жизнь | Броня | Оружие / тип брони | Атака/население / жизнь/население |
| --- | --- | ---: | ---: | ---: | ---: | --- | ---: |
${medianRows}

Сырые source ability metrics и медианы общих tooltip-полей взяты из pinned \`src/domain/combat/source-fixtures/ship-abilities.json\`. Проценты здесь сохраняют исходный tooltip text; сами по себе они не являются runtime-вероятностями. Роль Destroyer различается у источников трёх рас, поэтому новая Asterion aura Потрошителя +5% является отдельным решением.

| Pirate class / source slot | Aegis source abilities | Synod source abilities | Veyra source abilities | Общие метрики, значения источника и медиана |
| --- | --- | --- | --- | --- |
${sourceAbilityRows}

## Снимок характеристик NPC по уровням

Single-unit effective stats берутся из начального combat snapshot production resolver при levels 0/5/10 и соответствующем pirate technology profile; другие союзные стеки отсутствуют, поэтому aura не усиливает саму себя. Ability в последнем столбце — точный definition из текущего каталога.

| ID · уровень | Tech level | Атака/ед. | Жизнь/ед. | Броня | Способность (каталог) |
| --- | ---: | ---: | ---: | ---: | --- |
${statsRows}

## 90%-ный elimination budget

| Класс | Население корабля | Число | Фактический budget | Ошибка от 9,000 |
| --- | ---: | ---: | ---: | ---: |
${budgetRows}

Правило профиля: \`targetPopulation = round(sentCombatPopulation × 0.9)\`; число кораблей выбирается между floor и ceil, минимизируя абсолютную ошибку; равенство выбирает floor. Шесть строк используют отправленное combat population 10,000 и показывают ошибку моно-классового округления. Профиль не содержит оборону или planet-breaker.

## Seeded elimination исходы

Формат побед: attacker / draw / pirate defender. Остаток: медиана [наблюдаемый минимум–максимум] для player / pirate. В каждом matchup 95% Wilson interval приводится для каждой вероятности исхода.

| Score band | Pirate level | Player tech | Фракция | NPC класс | Player classes (formation/counter) | Player pop / pirate 90% target / actual (error) | Runs | W/D/L | Player win + 95% CI | Draw + 95% CI | Pirate win + 95% CI | Остаток player / pirate | Средние раунды | Seed hash |
| --- | ---: | ---: | --- | --- | --- | --- | ---: | --- | --- | --- | --- | --- | ---: | --- |
${matchupRows}

## Сходимость генерации тиров

Для каждого score point profile создаётся с отдельным deterministic owner × cycle seed. Интервал Wilson показывает долю возможного истинного среднего при данном размере набора; ожидаемая доля фиксируется score curve из кода.

| Общие очки | Resource points | Профили | Ожидаемые доли tier 1 / 2 / 3 | Наблюдаемые доли и 95% Wilson interval | Seed hash |
| ---: | ---: | ---: | --- | --- | --- |
${profileTierRows}

## Периодичность налётов

Для каждого fixed-coordinate schedule из текущего universe runtime считаются появившиеся контакты, у которых 15-минутная задержка roll попадает в горизонт. Каждый владелец × система × цикл проходит через текущий seeded \`resolvePirateRaidCycle\`; ${result.raidEstimates[0]?.owners ?? 1_000} синтетических владельцев для каждого q. «0 / 1 / 2+» считается отдельно по системе и владельцу. 95% Wilson interval приводится для доли system/owner с хотя бы одним рейдом. Seed-corpus содержит каждую пару owner × contact-cycle; независимые системы проверяются отдельными роллами.

Формулы реализации: \`q = resourcePoints / (resourcePoints + battlePoints)\` (при нулевой сумме q=0), \`chance = 0.02 + 0.10 × q\`, \`raidPopulationMultiplier = 0.35 + 0.55 × q\`. Контрольный срез для трёх независимых систем за один цикл:

| q | Вероятность на систему | Множитель населения | P(≥1) при 3 системах |
| ---: | ---: | ---: | ---: |
${qControlRows}

| q (chance) | Часы | Системы | Владельцы | Roll outcomes | Контактов на владельца | Рейдов/system / owner | Доля system 0 / 1 / 2+ [P≥1 CI] | Доля owner 0 / 1 / 2+ [P≥1 CI] | Диапазон рейдов/владельца | P(≥1) в одном цикле N систем | Seed hash |
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | ---: | ---: | --- |
${raidRows}

## Рейды планетолома у population-порога

Проверки используют gate \`totalPoints > 3,000,000 && targetPopulation < 2,000\`; owner score = 10,000,000. Обычный флот рейда с бюджетом \`round(target × 0.9)\` создаётся всегда; один планетолом добавляется в ${percentage(PIRATE_PLANET_BREAKER_APPEARANCE_CHANCE)} seeded роллов, не более одного. Все target snapshots сверяются с actual combat population: empty (0), fleet-only, defense-only, mixed (1,999/2,000). Потеря планеты требует победу атакующего, выживание планетолома и более одной планеты у владельца. Условный максимум destruction chance на уровне 10 — 15%; верхняя оценка на eligible рейд после 5%-го появления до учёта боя/выживания — 0.75%.

| Фракция | Тип защиты | Население | Pirate class | Score | Планетолом разрешён | Планетолом появился | Runs | Победы attacker / defender / ничьи + 95% CI | Остаток attacker / defender | Потеря планеты + 95% CI | Seed hash |
| --- | --- | ---: | --- | ---: | --- | --- | ---: | --- | --- | --- | --- |
${siegeRows}

## Ограничения и неизвестные

- Это Asterion resolver Monte Carlo с explicit seed, не Nemexia reference run. Ни сравнение с Nemexia, ни игровая parity не заявляются.
- Пер-полевые медианы не доказывают одинаковую эффективность рас; они создают нейтральный NPC baseline. Эффекты пиратских способностей остаются текущими Asterion implementations; Monte Carlo отражает их фактические результаты, но не калибрует их по скрытой серверной механике.
- Пустая колония проходит pirate-raid adapter как легальная цель с одной базовой единицей пиратского класса; в этой симуляции также проверяется empty defender в resolver. Миграции и офлайн-reconcile покрываются отдельно: старые/повреждённые pirate saves проверяет \`src/domain/pirates/state.test.ts\`, replay после reload и +15 минут контактного цикла — \`src/application/pirate-operations.test.ts\`, рейсы и их загрузку — \`src/application/flights.test.ts\`.
- Colony target snapshots in the siege sample are isolated fixtures. They do not model owner fleet production, flight timing, debris, persistence, or long-term economy. Raid-cycle counts use actual fixed-coordinate schedule and exact persisted roll function but assume contacts are not defeated early by outbound players.
- Residual ranges describe the sampled runs only. Sparse planet-loss outcomes at 1.5% have broad intervals; use the displayed Wilson interval, not a single-seed count.
- Balance acceptability is matchup-dependent: the tables show whether these sampled mirrors, counters, pairs and mixed forces have a possible winning route. They cannot prove that no composition or ability guarantees victory for all possible fleets.

## Воспроизводимость

Version: \`${PIRATE_BALANCE_SEED_CORPUS.version}\`; generation prefix: \`${PIRATE_BALANCE_SEED_CORPUS.prefix}\`; scenario key and run index map deterministically to each seed. Hashes are FNV-1a-32 over the ordered UTF-8 seed strings (newline after each). Regenerate with Node's built-in TypeScript stripping and the repository combat asset loader, then call \`runPirateBalanceSimulation({ runsPerMatchup: ${result.runsPerMatchup}, ownersForRaidEstimates: 1000 })\` and pass the result to \`formatPirateBalanceEvidence\`.
`;
}
