import type { ReportItem } from './types.ts';

// Presentation/foundation fixtures for systems that do not yet expose canonical
// runtime report events. Combat reports are never stored here: they are adapted
// directly from BattleHistoryState.
export const NON_COMBAT_REPORT_FIXTURES: readonly ReportItem[] = [
  {
    id: 'report-flight-patrol-returned',
    source: 'fixture',
    category: 'flights',
    typeLabel: 'Полёт',
    title: 'Патруль вернулся в Helion 01',
    preview: 'Маршрут завершён без происшествий.',
    body: 'Патрульная группа завершила плановый маршрут и вернулась на орбиту Helion 01. Состав группы не изменился.',
    timestamp: '2026-09-05T13:46:00.000Z',
    statusLabel: 'ЗАВЕРШЕНО',
    statusTone: 'success',
    participantNames: ['Патрульная группа'],
    planetNames: ['Helion 01'],
    coordinates: ['[1:1:1]'],
    details: [
      { label: 'Маршрут', value: 'Helion 01 → внешний патруль → Helion 01' },
      { label: 'Статус', value: 'Полёт завершён' },
      { label: 'Координаты', value: '[1:1:1]' },
    ],
  },
  {
    id: 'report-flight-route-ready',
    source: 'fixture',
    category: 'flights',
    typeLabel: 'Полёт',
    title: 'Маршрут транспортировки рассчитан',
    preview: 'Навигационный контур подготовил безопасный коридор.',
    body: 'Навигационный модуль рассчитал маршрут к внешнему сектору. Фактическая отправка флота в этом foundation-сообщении не выполняется.',
    timestamp: '2026-09-05T10:18:00.000Z',
    statusLabel: 'МАРШРУТ ГОТОВ',
    statusTone: 'info',
    participantNames: ['Навигационный контур'],
    planetNames: ['Helion 01'],
    coordinates: ['[1:5:8]'],
    details: [
      { label: 'Отправление', value: 'Helion 01' },
      { label: 'Цель', value: '[1:5:8]' },
      { label: 'Тип', value: 'Транспортный маршрут' },
    ],
  },
  {
    id: 'report-recon-varcon',
    source: 'fixture',
    category: 'recon',
    typeLabel: 'Разведка',
    title: 'Данные разведки: система Varcon',
    preview: 'Сканирование завершено. Получены полные навигационные данные.',
    body: 'Разведывательный контур завершил анализ системы Varcon. Зафиксированы навигационные объекты и безопасные точки выхода.',
    timestamp: '2026-09-05T12:38:00.000Z',
    statusLabel: 'ДАННЫЕ ПОЛУЧЕНЫ',
    statusTone: 'success',
    participantNames: ['Разведывательный контур'],
    planetNames: ['Varcon'],
    coordinates: ['[1:7:4]'],
    details: [
      { label: 'Система', value: 'Varcon' },
      { label: 'Координаты', value: '[1:7:4]' },
      { label: 'Разведданные', value: 'Полные для текущего сканирования' },
    ],
  },
  {
    id: 'report-recon-anomaly',
    source: 'fixture',
    category: 'recon',
    typeLabel: 'Разведка',
    title: 'Обнаружено аномальное образование',
    preview: 'Сигнатура требует отдельного изучения.',
    body: 'Сенсорная сеть обнаружила устойчивую аномальную сигнатуру за пределами орбиты. Источник пока не классифицирован.',
    timestamp: '2026-09-04T21:57:00.000Z',
    statusLabel: 'ТРЕБУЕТ АНАЛИЗА',
    statusTone: 'warning',
    participantNames: ['Сенсорная сеть'],
    planetNames: [],
    coordinates: ['[1:9:12]'],
    details: [
      { label: 'Класс', value: 'Неопределённая аномалия' },
      { label: 'Координаты', value: '[1:9:12]' },
      { label: 'Статус', value: 'Требует анализа' },
    ],
  },
  {
    id: 'report-economy-trade',
    source: 'fixture',
    category: 'economy',
    typeLabel: 'Экономика',
    title: 'Торговый отчёт: сделка завершена',
    preview: 'Поставка минералов подтверждена локальным журналом.',
    body: 'Экономический контур зарегистрировал завершение демонстрационной торговой операции. Это presentation fixture, а не связанный с runtime экономики event.',
    timestamp: '2026-09-05T11:51:00.000Z',
    statusLabel: 'ЗАВЕРШЕНО',
    statusTone: 'success',
    participantNames: ['Экономический контур'],
    planetNames: ['Helion 01'],
    coordinates: ['[1:1:1]'],
    details: [
      { label: 'Контур', value: 'Экономика' },
      { label: 'Планета', value: 'Helion 01' },
      { label: 'Источник', value: 'Presentation fixture' },
    ],
  },
  {
    id: 'report-economy-storage',
    source: 'fixture',
    category: 'economy',
    typeLabel: 'Экономика',
    title: 'Складской прогноз обновлён',
    preview: 'Система пересчитала прогноз заполнения складов.',
    body: 'Локальный аналитический модуль обновил прогноз вместимости складов на основной планете.',
    timestamp: '2026-09-04T18:12:00.000Z',
    statusLabel: 'ОБНОВЛЕНО',
    statusTone: 'info',
    participantNames: ['Экономический контур'],
    planetNames: ['Helion 01'],
    coordinates: ['[1:1:1]'],
    details: [
      { label: 'Планета', value: 'Helion 01' },
      { label: 'Тип', value: 'Складской прогноз' },
      { label: 'Источник', value: 'Presentation fixture' },
    ],
  },
  {
    id: 'report-construction-shipyard',
    source: 'fixture',
    category: 'construction',
    typeLabel: 'Строительство',
    title: 'Строительство завершено',
    preview: 'Космическая верфь переведена в рабочий режим.',
    body: 'Строительный контур зарегистрировал завершение демонстрационной стройки. Каноническая runtime-система событий строительства будет подключена отдельно.',
    timestamp: '2026-09-05T09:34:00.000Z',
    statusLabel: 'ГОТОВО',
    statusTone: 'success',
    participantNames: ['Строительный контур'],
    planetNames: ['Helion 01'],
    coordinates: ['[1:1:1]'],
    details: [
      { label: 'Объект', value: 'Космическая верфь' },
      { label: 'Планета', value: 'Helion 01' },
      { label: 'Источник', value: 'Presentation fixture' },
    ],
  },
  {
    id: 'report-construction-queue',
    source: 'fixture',
    category: 'construction',
    typeLabel: 'Строительство',
    title: 'Очередь строительства синхронизирована',
    preview: 'Локальный производственный журнал обновлён.',
    body: 'Система зафиксировала очередное состояние строительной очереди. Сообщение служит foundation-примером категории.',
    timestamp: '2026-09-04T15:03:00.000Z',
    statusLabel: 'СИНХРОНИЗИРОВАНО',
    statusTone: 'info',
    participantNames: ['Строительный контур'],
    planetNames: ['Helion 01'],
    coordinates: ['[1:1:1]'],
    details: [
      { label: 'Контур', value: 'Строительство' },
      { label: 'Планета', value: 'Helion 01' },
      { label: 'Источник', value: 'Presentation fixture' },
    ],
  },
  {
    id: 'report-diplomacy-channel',
    source: 'fixture',
    category: 'diplomacy',
    typeLabel: 'Дипломатия',
    title: 'Дипломатический канал обновлён',
    preview: 'Статус внешнего контакта синхронизирован.',
    body: 'Командный контур обновил информационный статус внешнего союза. Реальные дипломатические эффекты не рассчитываются этим report fixture.',
    timestamp: '2026-09-05T08:22:00.000Z',
    statusLabel: 'КАНАЛ ОТКРЫТ',
    statusTone: 'info',
    participantNames: ['Коалиция Аврора'],
    planetNames: [],
    coordinates: [],
    details: [
      { label: 'Контакт', value: 'Коалиция Аврора [AUR]' },
      { label: 'Статус', value: 'Информационный канал открыт' },
      { label: 'Источник', value: 'Presentation fixture' },
    ],
  },
  {
    id: 'report-diplomacy-tension',
    source: 'fixture',
    category: 'diplomacy',
    typeLabel: 'Дипломатия',
    title: 'Рост напряжённости на внешнем контуре',
    preview: 'Зафиксировано изменение статуса контакта.',
    body: 'Дипломатическая сводка отмечает рост напряжённости во внешнем секторе. Это presentation fixture без боевых или экономических модификаторов.',
    timestamp: '2026-09-04T13:28:00.000Z',
    statusLabel: 'ВНИМАНИЕ',
    statusTone: 'warning',
    participantNames: ['Железная Вуаль'],
    planetNames: [],
    coordinates: [],
    details: [
      { label: 'Контакт', value: 'Железная Вуаль [IVL]' },
      { label: 'Оценка', value: 'Напряжённость' },
      { label: 'Источник', value: 'Presentation fixture' },
    ],
  },
  {
    id: 'report-system-save',
    source: 'fixture',
    category: 'system',
    typeLabel: 'Системный',
    title: 'Локальное сохранение подтверждено',
    preview: 'Целостность текущего состояния проверена.',
    body: 'Системный журнал подтвердил доступность локального save envelope Asterion.',
    timestamp: '2026-09-05T07:41:00.000Z',
    statusLabel: 'СИСТЕМА ГОТОВА',
    statusTone: 'success',
    participantNames: ['Asterion Core'],
    planetNames: [],
    coordinates: [],
    details: [
      { label: 'Контур', value: 'Локальное сохранение' },
      { label: 'Статус', value: 'Доступно' },
      { label: 'Хранилище', value: 'asterion.vertical-slice.v1' },
    ],
  },
  {
    id: 'report-system-scan',
    source: 'fixture',
    category: 'system',
    typeLabel: 'Системный',
    title: 'Диагностика сенсорной сети завершена',
    preview: 'Критических отклонений не обнаружено.',
    body: 'Системная диагностика завершена без критических ошибок. Это deterministic fixture для Reports Center.',
    timestamp: '2026-09-04T11:06:00.000Z',
    statusLabel: 'НОРМА',
    statusTone: 'success',
    participantNames: ['Asterion Core'],
    planetNames: [],
    coordinates: [],
    details: [
      { label: 'Модуль', value: 'Сенсорная сеть' },
      { label: 'Результат', value: 'Норма' },
      { label: 'Источник', value: 'Presentation fixture' },
    ],
  },
  {
    id: 'report-inbox-command',
    source: 'fixture',
    category: 'inbox',
    typeLabel: 'Входящее сообщение',
    title: 'Сообщение от Командования флота',
    preview: 'Подготовлен новый координационный пакет.',
    body: 'Командование флота передало координационный пакет для следующего этапа подготовки. Фактический dispatch флота этим сообщением не запускается.',
    timestamp: '2026-09-05T12:09:00.000Z',
    statusLabel: 'ВХОДЯЩЕЕ',
    statusTone: 'info',
    participantNames: ['Командование флота'],
    planetNames: ['Helion 01'],
    coordinates: ['[1:1:1]'],
    details: [
      { label: 'Отправитель', value: 'Командование флота' },
      { label: 'Канал', value: 'Внутренний' },
      { label: 'Планета', value: 'Helion 01' },
    ],
  },
  {
    id: 'report-inbox-alliance',
    source: 'fixture',
    category: 'inbox',
    typeLabel: 'Входящее сообщение',
    title: 'Сводка союзного контура',
    preview: 'Получено обновление по совместным операциям.',
    body: 'Командный контур передал краткую сводку по текущим совместным операциям. Сообщение не является сетевым mailbox event.',
    timestamp: '2026-09-04T19:44:00.000Z',
    statusLabel: 'ВХОДЯЩЕЕ',
    statusTone: 'info',
    participantNames: ['Содружество Гелион'],
    planetNames: [],
    coordinates: [],
    details: [
      { label: 'Источник', value: 'Командование' },
      { label: 'Тип', value: 'Союзная сводка' },
      { label: 'Режим', value: 'Presentation fixture' },
    ],
  },
];