export const NEMEXIA_DESTROYER_REVIVAL_FIXTURES = {
  source: {
    officialHelpUrl: 'https://help.nemexia.com/en_EN/nemexia-new-2380-2430.html',
    officialHelpSection: 'Ships skills / Revival',
    archiveRoot: 'D:/Desktop/Nemexia/simulation-battles',
  },
  corpus: {
    savedReports: 1_369,
    reportsWithRepairEvents: 273,
    structuredRepairEntries: 648,
    unparsedRepairEntries: 0,
    reanimatorRepairEntries: 7,
    nonReanimatorRepairEntries: 641,
    nonReanimatorEntriesMatchingRoundedAmountFormula: 641,
    restoredShips: 11_609,
    expectedBeforeRounding: 11_610.466,
    eligibleTargetLossBuckets: 7_643,
    targetLossBucketsWithRepairEntry: 641,
    expectedEntriesAtDocumentedChance: 622.15,
    eligibleSideRounds: 1_938,
    sideRoundsWithAtLeastOneRepairEntry: 525,
    nonterminalEntriesWithObservedNextRoundDestroyerCount: 624,
    terminalEntriesWithDestroyerCountEstimatedFromActionRows: 17,
  },
  formula: {
    chancePerFunctioningDestroyer: 0.0014,
    maximumChance: 0.7,
    bonusPerFunctioningDestroyer: 0.0008,
    maximumRevivedShare: 0.4,
    amountRounding: 'nearest integer, half-up',
    archiveSupportsIndependentTargetStackOpportunity: true,
    exactRollGranularityProven: false,
  },
  examples: [
    {
      report: 'reports/3203f5167424/0003_science150-7-r1-max/page.html',
      round: 2,
      side: 'defender',
      destroyersAtRoundStart: 117,
      destroyersLostDuringRound: 18,
      functioningDestroyersAfterRound: 99,
      observations: [
        { target: 'Cruiser', casualtiesDuringRound: 126, repaired: 10, expectedUnrounded: 9.9792, repairReportLine: 967, amountReportLine: 969 },
        { target: 'Protector', casualtiesDuringRound: 93, repaired: 7, expectedUnrounded: 7.3656, repairReportLine: 973, amountReportLine: 975 },
      ],
      nextRoundDestroyerRosterLine: 1008,
    },
    {
      report: 'reports/a5449dc74a9b/0019_recon240-race-r3-r1-zero-r1/page.html',
      round: 2,
      side: 'defender',
      destroyersAtRoundStart: 94,
      destroyersLostDuringRound: 45,
      functioningDestroyersAfterRound: 49,
      observations: [
        { target: 'Cruiser', casualtiesDuringRound: 179, repaired: 7, expectedUnrounded: 7.0168, repairReportLine: 975, nextRoundRosterLine: 1012 },
      ],
      nextRoundDestroyerRosterLine: 1004,
    },
  ],
} as const;
